spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Configuration par défaut pour tous les profils
  jpa:
    properties:
      hibernate:
        format_sql: true

  # Mise en cache activée par défaut
  cache:
    type: simple
